In [1]:
import numpy

In [2]:
from tensorflow.keras.models import load_model

In [3]:
import tensorflow

In [4]:
from tensorflow.keras.datasets import mnist

In [5]:
from tensorflow.keras.models import Sequential

In [6]:
from tensorflow.keras import layers    

In [7]:
from tensorflow.keras.layers import  Dense,Flatten

In [8]:
from tensorflow.keras.layers import Conv2D

In [9]:
from keras.optimizers import  Adam

In [10]:
from keras.utils import np_utils

In [11]:
import matplotlib.pyplot as plt

In [12]:
import numpy as np

In [13]:
from tensorflow.keras.optimizers import SGD

In [14]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [15]:
#print(x_train.shape)

In [16]:
#print(x_test.shape)

In [17]:
#print(y_train)

In [18]:
#print(y_train.shape)

In [19]:
#print(y_test.shape)

In [20]:
#plt.imshow(x_train[0])

In [21]:
#Reshping the data for CNN
x_train = x_train.reshape(60000,28,28,1).astype("float32")
x_test = x_test.reshape(10000,28,28,1).astype("float32")
#print(x_train)
#print(x_test)

In [22]:
#Changing the encoding type into ONE HOT ENCODING
ClassCount = 10
y_train = np_utils.to_categorical(y_train,ClassCount)
y_test = np_utils.to_categorical(y_test,ClassCount)
print(y_train)
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [23]:
#Creating Sequential model
Model = Sequential()

In [24]:
#Adding Layer to the Sequential Model with Rectified Linear Unit activation function(NORMALIZATION)
Model.add(Conv2D(64,(3,3), input_shape = (28,28,1),activation = 'relu'))
Model.add(Conv2D(32,(3,3), activation= 'relu'     ))          

In [25]:
#Adding Layer to the Sequential Model to Flatten the image matrix
Model.add(Flatten())

In [26]:
#Adding Layer to the  Sequential Model with Softmax activation function
Model.add(Dense(ClassCount,activation='softmax'))

In [27]:
Model.compile(loss='categorical_crossentropy',optimizer="SGD",metrics=['accuracy'])

In [29]:
Model.fit(x_train,y_train,validation_data = (x_test,y_test),epochs = 70,batch_size = 64,validation_split = 0.2)

Epoch 1/70
938/938 [==============================] - 23s 25ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 2/70
938/938 [==============================] - 23s 25ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 3/70
938/938 [==============================] - 24s 26ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 4/70
938/938 [==============================] - 25s 26ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 5/70
938/938 [==============================] - 25s 26ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 6/70
938/938 [==============================] - 24s 26ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 7/70
938/938 [==============================] - 25s 26ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy:

938/938 [==============================] - 25s 27ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 58/70
938/938 [==============================] - 25s 26ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 59/70
938/938 [==============================] - 25s 26ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 60/70
938/938 [==============================] - 25s 26ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 61/70
938/938 [==============================] - 25s 27ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 62/70
938/938 [==============================] - 25s 26ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.1135
Epoch 63/70
938/938 [==============================] - 26s 27ms/step - loss: 2.3012 - accuracy: 0.1124 - val_loss: 2.3010 - val_accuracy: 0.11

In [31]:
Metrics = Model.evaluate(x_test,y_test,verbose=1)
print("Test Losss and Test accuracy")
print(Metrics)

313/313 [==============================] - 2s 8ms/step - loss: 2.3010 - accuracy: 0.1135
Test Losss and Test accuracy
[2.301020383834839, 0.11349999904632568]


In [32]:
Prediction = Model.predict(x_test[:4])
print(Prediction)
print(np.argmax(Prediction,axis=1))
print(y_test[:4])


1/1 [==============================] - 0s 310ms/step
[[0.09854448 0.11213045 0.09960271 0.10226054 0.09733802 0.09045285
  0.09900323 0.10410815 0.09747919 0.0990804 ]
 [0.09854448 0.11213045 0.09960271 0.10226054 0.09733802 0.09045285
  0.09900323 0.10410815 0.09747919 0.0990804 ]
 [0.09854448 0.11213045 0.09960271 0.10226054 0.09733802 0.09045285
  0.09900323 0.10410815 0.09747919 0.0990804 ]
 [0.09854448 0.11213045 0.09960271 0.10226054 0.09733802 0.09045285
  0.09900323 0.10410815 0.09747919 0.0990804 ]]
[1 1 1 1]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [33]:
#Saving the model
Model.save('models/mnistCNN.h5')